server:
  port: 8761

spring:
  application:
    name: eureka-server
  # Zipkin Properties
  zipkin:
    base-url: http://18.217.148.69:9411
  # Sleuth Properties
  sleuth:
    sampler:
      probability: 1.0

# Eureka Properties
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: 18.217.148.69
    prefer-ip-address: true
