spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: movieService
          uri: lb://MOVIESERVICE
          predicates:
            - Path=/api/movie/**
        - id: userService
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/user/**
        - id: eureka-server
          uri: http://18.217.148.69:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://18.217.148.69:8761
          predicates:
            - Path=/eureka/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

  zipkin:
    base-url: http://18.217.148.69:9411

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@18.217.148.69:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

server:
  port: 8080
  compression:
    enabled: true
  ssl:
    enabled: false
    
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

